FROM ghcr.io/catthehacker/ubuntu@sha256:62d572b92f9f32d3427b6d220ad1f9dca9c7b6ffad37d295425037dbff78abaf
COPY less.deb /tmp/runback-less.deb
RUN dpkg -i /tmp/runback-less.deb && rm /tmp/runback-less.deb
